### ISSUE TITLE
Revamp Proceedural Generation

### ISSUE THREAD

**Issue by klay2000** [wibbywobblytimeywimeystuff/SUPERROUGUELIKEFUSION#14]
I CANT WORK WITH THIS DUCT TAPED TOGETHER ALGORITHM ANYMORE!!!!! (softly cries)

**Comment by klay2000** [comment]
Nikhil I can't keep on proceedural generation, can u do it???

**Comment by SpockTheLogical7** [comment]
I'll try.

**Comment by klay2000** [comment]
wile ur in there add random monster spawning

**Comment by klay2000** [comment]
nvm, I'll just get the monster spawning
